# Generated by Django 4.0.6 on 2022-07-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='select',
            field=models.CharField(choices=[('Show', 'Show'), ('Event', 'Event'), ('Talent', 'Talent'), ('Rent', 'Rent'), ('Contact', 'Contact'), ('Post', 'Post')], default='tweet', max_length=100),
        ),
    ]
